name: CI
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: sudo apt-get update -qq &&
          sudo apt-get install -qq
          ninja-build python3-pip
          device-tree-compiler
      - name: Install meson
        run: pip3 install --user meson
      - name: Install clang
        uses: KyleMayes/install-llvm-action@v2.0.9
        with:
          version: "21"
      - name: Check clang-format
        run: meson setup build-lint && ninja -C build-lint clang-format-check
      - name: Check meson format
        run: meson format --check-only --recursive

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Update archive
        run: sudo apt-get update -qq
      - name: Install dependencies
        run: sudo apt-get install -qq
          gcc
          gcc-arm-linux-gnueabi libc-dev-armel-cross
          git device-tree-compiler qemu-user
          python3-pip ninja-build
      - name: Install minimum meson
        run: pip3 install --user meson~=0.63
      - uses: actions/checkout@v2
      - name: arm32
        # meson compile requires 0.54, but Ubuntu 20.04 ships 0.53, so run ninja directly
        run: meson setup build-arm --cross-file meson/arm-linux-gnueabi-gcc.ini && ninja -C build-arm
      - name: native
        run: meson setup build-native && ninja -C build-native

